spring.application.name=TodoListPlus-Back2-1
#MYSQL
spring.datasource.url=jdbc:mysql://localhost:3306/sample_schema
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
